use crate::{
    app::MessageType,
    entries::{Entry, ResultLine},
    screen::Mode,
};

#[derive(Debug, Clone, PartialEq)]
pub enum Action {
    Tick,
    Render,
    Resize(u16, u16),
    CursorUp,
    CursorDown,
    CursorToTop,
    CursorToBottom,
    DirectoryOpenSelected,
    DirectoryLeave,
    Message(String, MessageType),
    ToggleHelp,
    CloseHelp,
    ScriptRunning(Entry),
    ScriptFinished(Entry, u128),
    ScriptError(Entry, String),
    SelectCurrent,
    SelectAllAfter,
    SelectAllInDirectory,
    SelectScripts(Vec<Entry>),
    AppendScripts(Vec<Entry>),
    ScriptHighlighted(Option<ResultLine>),
    RemoveSelectedScript,
    RemoveScript(Entry),
    RemoveAllSelectedScripts,
    SwitchMode(Mode),
    ScriptRun,
    Suspend,
    Resume,
    Quit,
    Refresh,
    Error(String),
    Help,
}
