use crate::{app::Script, screen::Mode};

#[allow(unused)]
#[derive(Debug, Clone, PartialEq)]
pub enum Action {
    Tick,
    Render,
    Resize(u16, u16),
    CursorUp,
    CursorDown,
    CursorToTop,
    CursorToBottom,
    DirectoryOpenSelected,
    DirectoryLeave,
    ToggleHelp,
    CloseHelp,
    ScriptRunning(String),
    ScriptFinished(String, u128),
    ScriptError(String, String),
    SelectCurrent,
    SelectAllAfter,
    SelectAllInDirectory,
    UnselectAll,
    UnselectCurrent,
    AddSelection(Vec<String>),
    RemoveSelection(Vec<String>),
    ToggleSelection(Vec<String>),
    SelectionChanged(Vec<String>),
    ScriptHighlighted(Option<Script>),
    SwitchMode(Mode),
    ScriptRun,
    Suspend,
    Resume,
    Quit,
    Refresh,
    Error(String),
    Help,
}
