use crate::{app::MessageType, entries::Entry, screen::Mode};

#[derive(Debug, Clone, PartialEq)]
pub enum Action {
    Tick,
    Render,
    Resize(u16, u16),
    CursorUp,
    CursorDown,
    CursorToTop,
    CursorToBottom,
    DirectoryOpenSelected,
    DirectoryLeave,
    Message(String, MessageType),
    SelectCurrent,
    SelectAllAfter,
    SelectAllInDirectory,
    SelectScripts(Vec<Entry>),
    AppendScripts(Vec<Entry>),
    RemoveSelectedScript,
    RemoveScript(Entry),
    RemoveAllSelectedScripts,
    RunScripts,
    SwitchMode(Mode),
    StartSpinner,
    StopSpinner,
    ScriptRun,
    Suspend,
    Resume,
    Quit,
    Refresh,
    Error(String),
    Help,
}
